spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/snapfix
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: your-very-secret-key-that-is-at-least-32-bytes-long
  expiration: 900000